# Generated by Django 3.0.6 on 2020-08-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logoUri', models.ImageField(upload_to='')),
                ('clubState', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Team',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('imageUri', models.ImageField(upload_to='')),
                ('playerJerseyNumber', models.IntegerField()),
                ('country', models.CharField(max_length=15)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.Team')),
            ],
            options={
                'db_table': 'Player',
                'ordering': ('firstName',),
            },
        ),
    ]
