# Generated by Django 3.0.6 on 2020-08-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=20)),
                ('team2', models.CharField(max_length=20)),
                ('winner', models.CharField(max_length=20)),
                ('ccreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Matches',
                'ordering': ('winner',),
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('matches_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('points', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Points',
                'ordering': ('team_name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logoUri', models.ImageField(upload_to='')),
                ('clubState', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Team',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('imageUri', models.ImageField(upload_to='')),
                ('playerJerseyNumber', models.IntegerField()),
                ('country', models.CharField(max_length=15)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.Team')),
            ],
            options={
                'db_table': 'Player',
                'ordering': ('firstName',),
            },
        ),
    ]
