# Generated by Django 3.0.6 on 2020-08-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('matches_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('points', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
