# Generated by Django 3.0.6 on 2020-08-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'ordering': ('team_name',)},
        ),
        migrations.AlterModelTable(
            name='points',
            table='Points',
        ),
    ]
